/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./templates/**/*.html"],
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#adc7f7",
        "surface-container-low": "#f1f4f6",
        "primary-container": "#1a365d",
        "on-primary-fixed": "#001b3c",
        "inverse-on-surface": "#eef1f3",
        "outline": "#74777f",
        "on-tertiary-fixed-variant": "#3d4759",
        "on-secondary-fixed": "#00201f",
        "on-surface-variant": "#43474e",
        "surface-variant": "#e0e3e5",
        "primary": "#002045",
        "surface-container": "#ebeef0",
        "secondary-container": "#91f0ed",
        "on-background": "#181c1e",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#bdc7dc",
        "surface-bright": "#f7fafc",
        "on-error-container": "#93000a",
        "tertiary": "#172131",
        "on-primary-container": "#86a0cd",
        "primary-fixed-dim": "#adc7f7",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#121c2c",
        "on-error": "#ffffff",
        "on-tertiary-container": "#959fb3",
        "on-secondary": "#ffffff",
        "outline-variant": "#c4c6cf",
        "surface": "#f7fafc",
        "on-secondary-container": "#006e6d",
        "error": "#ba1a1a",
        "background": "#f7fafc",
        "secondary": "#006a68",
        "surface-container-high": "#e5e9eb",
        "surface-dim": "#d7dadc",
        "inverse-surface": "#2d3133",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#00504e",
        "tertiary-fixed": "#d9e3f9",
        "secondary-fixed": "#94f2f0",
        "surface-container-highest": "#e0e3e5",
        "on-surface": "#181c1e",
        "secondary-fixed-dim": "#77d6d3",
        "tertiary-container": "#2c3647",
        "on-primary-fixed-variant": "#2d476f",
        "surface-tint": "#455f88",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#d6e3ff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "margin-mobile": "16px",
        "stack-md": "24px",
        "margin-desktop": "40px",
        "gutter": "24px",
        "unit": "8px",
        "stack-xs": "4px",
        "container-max": "1280px",
        "stack-lg": "48px",
        "stack-sm": "12px",
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "title-lg": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "title-lg": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-sm": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600" }],
        "headline-md": ["30px", { lineHeight: "38px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};
